### PR TITLE
Various things

### PR DESCRIPTION
**Pull request by davelab6**
This doesn't effect the design at all, or the font file much, its just adminitrivia

### CODE REVIEW

**Comment by davelab6** [comment]
This doesn't effect the design at all, or the font file much, its just adminitrivia

**Comment by davelab6** [comment]
Fixed the name error :)

**Comment by lironlavitur** [comment]
thank you!

On Wed, Mar 2, 2016 at 9:34 PM, Dave Crossland notifications@github.com
wrote:

> Fixed the name error :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shinntype/bellefair/pull/2#issuecomment-191389719.

## 

Liron Lavi Turkenich
Type & Graphic Design, Research

+972-544872265
www.lironlavi.com
@LironLaviTur https://twitter.com/LironLaviTur
Aravrit https://www.facebook.com/aravrit?ref=aymt_homepage_panel, one
script, two languages

**Comment by nickshinn** [comment]
Thanks Dave.

**Pull request merged**
